Fw 2687 v 2 be include site visibility in get site response
First-Peoples-Cultural-Council/fv-web-ui pull request #1377
Opened 2022-08-23 21:11 UTC by sahil97

- Added visibility as an attribute in the Site object
- Added a funciton to convert state to visibility in the StateUtils file
- The getSite API now returns visibility in the respone
- Added test for the getSite response to include visibility

2022-08-24 22:23 UTC, sarahfirstvoices requested changes

2022-08-25 17:08 UTC, sarahfirstvoices commented on modules/api/firstvoices-rest-api/src/test/java/org/nuxeo/ecm/restapi/server/jaxrs/firstvoices/SitesObjectTest.java
> +  public void TestVisibility() throws IOException {
Sorry to be so fussy about this, but can you please make this start with a lowercase letter? Capitalized names are generally reserved for classes

2022-08-25 17:33 UTC, sahil97 commented on modules/api/firstvoices-rest-api/src/test/java/org/nuxeo/ecm/restapi/server/jaxrs/firstvoices/SitesObjectTest.java
> +  public void TestVisibility() throws IOException {
Yes, my bad. I misspelled it, I meant it to be camelCased in the first place.

2022-08-26 15:54 UTC, sarahfirstvoices approved these changes
Looks good! Thanks for making those changes

2022-08-26 18:02 UTC, merged