Added audio upload support
First-Peoples-Cultural-Council/fv-web-ui pull request #1490
Opened 2022-10-26 22:31 UTC by sahil97

#### Definition of Done
- [ ] Acceptance criteria has been met
- [ ] Postman endpoint with example has been created

2022-11-01 21:47 UTC, sarahfirstvoices commented on frontend/app_v2/src/common/constants/docTypes.js
>  export const SUPPORTED_IMAGE_EXTENSIONS = ['jpeg', 'png', 'gif', 'tiff']
I know this isn't part of this review, but does uppy handle variations on these file extensions, like jpg and tif?

2022-11-02 15:39 UTC, sahil97 commented on frontend/app_v2/src/common/constants/docTypes.js
>  export const SUPPORTED_IMAGE_EXTENSIONS = ['jpeg', 'png', 'gif', 'tiff']
Good point. I can check

2022-11-08 18:28 UTC, sarahfirstvoices requested changes
Best solution is probably to switch from file extensions to mime types

2022-11-08 23:27 UTC, sahil97 commented on frontend/app_v2/src/common/constants/docTypes.js
>  export const SUPPORTED_IMAGE_EXTENSIONS = ['jpeg', 'png', 'gif', 'tiff']
Added extensions manually instead of the mime type to be more specific.

2022-11-08 23:30 UTC, sarahfirstvoices approved these changes

2022-11-08 23:32 UTC, merged