Fw 3781 crud for fv person
First-Peoples-Cultural-Council/fv-web-ui pull request #1505
Opened 2022-11-02 22:24 UTC by sahil97

#### Definition of Done
- [ ] Acceptance criteria has been met
- [ ] Postman endpoint with example has been created

2022-11-07 21:44 UTC, sarahfirstvoices requested changes

2022-11-07 21:44 UTC, sarahfirstvoices commented on modules/common/firstvoices-core-tests/src/main/java/ca/firstvoices/tests/mocks/services/MockDialectServiceImpl.java
>          // Alternate 1 and 2 speakers
Hmm, these media properties might need rethinking. The version in master matched the v1 data, but the changes needed for v2 are more complicated than just swapping contributors for persons. I think all the new fields have been implemented at the schema level now, so you could make the mock data generator match the v2 format. Details are on the v2 field mapping wiki page: https://firstvoices.atlassian.net/wiki/spaces/FIR/pages/79691807/V2+Data+Migration+Field+Mapping#FVAudio-FVImage-&-FVVideo

2022-11-07 21:44 UTC, sarahfirstvoices commented on modules/common/firstvoices-data/src/main/resources/data/schemas/fvdictionary.xsd
> +  </xs:element>
I don't think this is needed. The only place we currently plan to use FVPerson is for the speaker property of FVAudio documents. See the FVContributor migration plan for details: https://firstvoices.atlassian.net/wiki/spaces/FIR/pages/61341697/FVContributor+migration+plan#Fields-to-migrate

2022-11-07 21:44 UTC, sarahfirstvoices commented on modules/common/firstvoices-publisher/src/main/java/ca/firstvoices/publisher/services/FirstVoicesSyncStateServiceImpl.java
> +      String[] parents = new String[]{FV_RESOURCES_NAME, FV_CATEGORIES_NAME, FV_PHRASE_BOOKS_NAME, FV_PERSONS_NAME};
What does this do? Are we sure it isn't still used in v1? I wouldn't want to mess up the contributor data that is still coming in from v1

2022-11-07 21:44 UTC, sarahfirstvoices commented on modules/security/firstvoices-security-user-registration/src/main/resources/OSGI-INF/extensions/ca.firstvoices.usermapping.xml
> +        userAttributes.put("persons", userObject.persons);
Are you sure this is the same "contributors" as FVContributors? I'm not sure we should be having to edit anything about users for this.

2022-11-07 21:44 UTC, sarahfirstvoices commented on modules/security/firstvoices-security-user-registration/src/main/resources/schemas/fvuser.xsd
> +
Same comment as above-- are we sure fvuser:contributors is related to this change?

2022-11-07 23:06 UTC, sahil97 commented on modules/common/firstvoices-publisher/src/main/java/ca/firstvoices/publisher/services/FirstVoicesSyncStateServiceImpl.java
> +      String[] parents = new String[]{FV_RESOURCES_NAME, FV_CATEGORIES_NAME, FV_PHRASE_BOOKS_NAME, FV_PERSONS_NAME};
So from the comments, I believe this service ensures when we are transitioning any object to a different state, all these linked objects are also transitioned to that state.
You are right that this should not impact Persons ( and I guess should not included contributors ? as their state needs to be managed independently ?)
Reverting this back.

2022-11-08 18:12 UTC, sarahfirstvoices requested changes

2022-11-08 18:12 UTC, sarahfirstvoices commented on modules/common/firstvoices-core-tests/src/main/java/ca/firstvoices/tests/mocks/services/MockDialectServiceImpl.java
>          // Alternate 1 and 2 speakers
Setting e.g., the image recorder to a person is still not going to give very good results, I think. It will be broken in both v1 and v2. I think we should make all the media data match the v2 format. So instead of including any fvm:recorder or fvm:source properties, the audio should have fvaudio:speakers and all 3 types should have fvm:acknowledgement

2022-11-08 23:30 UTC, sarahfirstvoices approved these changes

2022-11-08 23:48 UTC, merged