Fw 3817 validate speaker ids for media uploads
First-Peoples-Cultural-Council/fv-web-ui pull request #1516
Opened 2022-11-09 21:45 UTC by sahil97

#### Definition of Done
- [ ] Acceptance criteria has been met
- [ ] Postman endpoint with example has been created

2022-11-14 21:28 UTC, sarahfirstvoices requested changes

2022-11-14 21:28 UTC, sarahfirstvoices commented on modules/api/firstvoices-rest-api/src/main/java/ca/firstvoices/rest/helpers/DocumentUtils.java
> +  public static DocumentModel getValidatedParentDocument(WebContext context, String parentDocumentId) throws DocumentNotFoundException {
I don't think the "parent document" language makes sense outside of the MediaUploadObject. If this is going to be a reusable public util function, I think it should just be called getValidatedDocument, and then the error message will need to be handled in MediaUploadObject

2022-11-14 21:28 UTC, sarahfirstvoices commented on modules/api/firstvoices-rest-api/src/main/java/ca/firstvoices/rest/helpers/DocumentUtils.java
> +    }
This bit of checking would be more clear if it was extracted to a function called something like hasDialect(documentId, dialectId) or validateDocumentHasDialect. I think you could also add a specific message for the exception, something like "Document [123] does not have the expected parent [456]."

2022-11-14 21:28 UTC, sarahfirstvoices commented on modules/api/firstvoices-rest-api/src/main/java/ca/firstvoices/rest/helpers/DocumentUtils.java
> +public class DocumentUtils {
Please add unit tests for this class.

2022-11-14 21:28 UTC, sarahfirstvoices commented on modules/api/firstvoices-rest-api/src/main/java/ca/firstvoices/rest/helpers/DocumentUtils.java
> +  }
Now that these functions are all collected into one class, I notice they don't all have consistent names and behaviour. This will make them harder to use and harder to maintain. Let's chat about how to standardize them.

Specific questions:
- can functions with matching names have matching behaviour? E.g., getValidatedX means it returns a value or throws an exception, while validateX is void but may throw an exception.
- does it make sense to generate all these exceptions in a utility class, or should they be handled by the consumers?

2022-11-14 21:28 UTC, sarahfirstvoices commented on modules/api/firstvoices-rest-api/src/main/java/ca/firstvoices/rest/helpers/DocumentUtils.java
> +  public static URL getValidatedUrl(String urlString) {
This function has nothing to do with documents and doesn't really belong here. Is it being reused, or could it go back where it came from?

2022-11-14 21:28 UTC, sarahfirstvoices commented on modules/api/firstvoices-rest-api/src/main/java/ca/firstvoices/rest/helpers/DocumentUtils.java
> +  public static boolean validateSpeakerId(WebContext context, String speakerId, DocumentModel parentDoc) throws IllegalArgumentException {
Not sure this function belongs here-- it's more specific than "DocumentUtils" would suggest, and we are only using it in one place. Should it be in MediaUploadObject instead?

2022-11-14 21:28 UTC, sarahfirstvoices commented on modules/api/firstvoices-rest-api/src/main/java/org/nuxeo/ecm/restapi/server/jaxrs/firstvoices/AbstractSearchlikeObject.java
> -  protected String validateDocumentType(String docId, String type) throws IllegalArgumentException {
You could consider keeping this function as a little wrapper that passes the session to the utility function.

2022-11-14 23:00 UTC, sahil97 commented on modules/api/firstvoices-rest-api/src/main/java/ca/firstvoices/rest/helpers/DocumentUtils.java
> +  }
I believe it can be like you mentioned in your first point, but the validateX also returns true if file is of valid type, instead of boolean. Then we can also use it in conditional clauses.
What do you think ?
I'm not sure on the exceptions part, should it be like the utility classes generate exceptions and the consumer handles them or adds messages and then forward them to their parent ?

2022-11-15 17:30 UTC, sarahfirstvoices commented on modules/api/firstvoices-rest-api/src/main/java/ca/firstvoices/rest/helpers/DocumentUtils.java
> +  }
Boolean instead of void for the validateX methods sounds good to me.

And I think since all these methods have validate in the name and are intended to check values we expect to be correct, it's appropriate to throw exceptions. Not sure IllegalArgumentException is quite right, but it's good enough

2022-11-17 18:53 UTC, sarahfirstvoices commented on modules/api/firstvoices-rest-api/src/main/java/org/nuxeo/ecm/restapi/server/jaxrs/firstvoices/MediaUploadObject.java
> +    if(mediaDocType.equals(FV_AUDIO)){
This could go even earlier. There's no need to even download the file if the parameters are invalid, so you can move this validation up to line 119-ish, as soon as you know the media type.

2022-11-17 18:56 UTC, sarahfirstvoices commented on modules/api/firstvoices-rest-api/src/test/java/org/nuxeo/ecm/restapi/server/jaxrs/firstvoices/DocumentUtilsTest.java
> +  @Test
This is fine the way it is, but to save effort in the future there's no need to test multiple document types here, since they don't exercise any different lines of code. One success response and one of each type of failure would be enough

2022-11-17 18:58 UTC, sarahfirstvoices commented on modules/api/firstvoices-rest-api/src/test/java/org/nuxeo/ecm/restapi/server/jaxrs/firstvoices/DocumentUtilsTest.java
> +  public void validateDocumentTypeTest_wrongObjectType() {
Another type of failure we should test here is if the document id is not valid (document not found)

2022-11-17 19:00 UTC, sarahfirstvoices commented on modules/api/firstvoices-rest-api/src/test/java/org/nuxeo/ecm/restapi/server/jaxrs/firstvoices/MediaUploadSpeakerValidationTest.java
> +    }
If this doesn't throw an error does the test fail? I think it needs a failing assertion after the catch block, just in case

2022-11-17 19:01 UTC, sarahfirstvoices commented on modules/api/firstvoices-rest-api/src/test/java/org/nuxeo/ecm/restapi/server/jaxrs/firstvoices/MediaUploadSpeakerValidationTest.java
> +    }
Same for the other error tests below

2022-11-17 19:03 UTC, sarahfirstvoices commented on modules/api/firstvoices-rest-api/src/main/java/org/nuxeo/ecm/restapi/server/jaxrs/firstvoices/MediaUploadObject.java
> +        String errorMsg = "Invalid speaker Id(s): Please verify Speaker Ids and the associated Dialect";
Looks great, thanks for these edits

2022-11-17 22:15 UTC, sahil97 commented on modules/api/firstvoices-rest-api/src/test/java/org/nuxeo/ecm/restapi/server/jaxrs/firstvoices/MediaUploadSpeakerValidationTest.java
> +    }
Good catch. Didn't think of the passing case.

2022-11-17 23:47 UTC, sarahfirstvoices approved these changes

2022-11-18 21:15 UTC, merged