FW-1563
First-Peoples-Cultural-Council/fv-web-ui pull request #583
Opened 2020-11-10 23:25 UTC by elysse-fpcc

- Added code to generate 5 songs and 5 stories of variable lengths
- Each song/story has randomly generated title/introduction/page content of varying sizes
- Also added a new document "contributor" for use in Songs/Stories as well as in future improvements on mock data 
- Updated tests to test for these new document types

2020-11-16 20:21 UTC, dy2288 requested changes
Great job overall @elysse-fpcc - see proposed changes though.

2020-11-16 20:21 UTC, dy2288 commented on FirstVoicesCoreTests/src/main/java/ca/firstvoices/tests/mocks/services/MockDialectServiceImpl.java
> +      String[] contributorsArray = {"Contributor"};
Don't think setting `dc:contributors` is needed here?

2020-11-16 20:21 UTC, dy2288 commented on FirstVoicesCoreTests/src/main/java/ca/firstvoices/tests/mocks/services/MockDialectServiceImpl.java
> +      int numPages = ThreadLocalRandom.current().nextInt(0, 5);
For the purposes of setting mock data for something like cypress, it probably makes sense to always have at least one page generated?

2020-11-16 20:21 UTC, dy2288 commented on FirstVoicesCoreTests/src/main/java/ca/firstvoices/tests/mocks/services/MockDialectServiceImpl.java
> +  private DocumentModelList generateFVStories(CoreSession session, String path, int storyEntries,
Aside from the line that sets the type and the variable names (e.g. `storyDoc.setPropertyValue("fvbook:type", "story");`) - this and the generateFVSongs() methods are pretty much identical. I would avoid the duplication by creating a generic method to handle the creation of a book, that can accept the type (song/story).

Then call it in here, e.g.:
```java
private DocumentModelList generateFVStories(CoreSession session, String path, int storyEntries,
String[] wordsToUse) {
   createBook(session, 'story');
}
```

and 

```java
private DocumentModelList generateFVSongs(CoreSession session, String path, int storyEntries,
String[] wordsToUse) {
   createBook(session, 'song');
}
```

2020-11-17 21:43 UTC, elysse-fpcc commented
Thanks for the review and feedback @dy2288 - made the requested changes :)

2020-11-17 23:43 UTC, dy2288 approved these changes
Looks great! Approved

2020-11-18 00:03 UTC, merged